
version: '3'

services:
  dex:
    image: partitio/dex:logout
    restart: always
    command:
    - dex
    - serve
    - /etc/dex/config.yaml
    environment:
    - "DEX_EXPAND_ENV=false"
    - "DEX_SESSION_AUTHKEY=90bc891caf30f994c2fc18663ad8394e"
    - "DEX_SESSION_ENCKEY=8b13ebf9c3bfebfd63863fc841a6d473"
    - "DEX_SESSION_DOMAIN=example.localhost"
    ports:
    - 5556:5556
    volumes:
    - ./example-test/dex.yaml:/etc/dex/config.yaml

